PID:
  P:
    min: -10000
    max: 10000
    default: 0
    type: "double"
    description: "P"
  I:
    min: -10000
    max: 10000
    default: 0
    type: "double"
    description: "I"
  D:
    min: -10000
    max: 10000
    default: 0
    type: "double"
    description: "D"
  reset_robot:
    default: true
    type: "bool"
    description: "reset robot"
  logfile:
    default: "temp.csv"
    type: "string"
    description: "log name"
  logenable:
    default: false
    type: "bool"
    description: "log enable"
