- double:
    name: enemy_about_to_steal_ball_distance
    min: 0.0
    max: 1.0
    value: 0.27
    description: >-
        How far in front of a friendly robot an enemy robot must be to be considered a thread
        of immediately stealing the ball

- double:
    name: min_open_angle_for_shot_deg
    min: 0.0
    max: 90.0
    value: 6
    description: The minimum open angle to the goal that we require before taking a shot
