package(default_visibility = ["//visibility:public"])

filegroup(
    name = "STM32H7xx_HAL_Driver",
    srcs = [
        "STM32H7xx_HAL_Driver",
    ],
)

#cc_library(
#    name = "STM32H7xx_HAL_Driver",
#    srcs = glob([
#        "Src/*.c",
#    ]),
#    hdrs = glob([
#        "Inc/*.h",
#    ]),
#    includes = ["./Inc"],
#)
