
/**
 *  !! WARNING !!
 *
 *  THIS FILE IS AUTOGENERATED, ANY CHANGES MADE WILL BE LOST
 *
 *  !! WARNING !!
 */

#include <dynamic_reconfigure/server.h>
#include <ros/ros.h>
#include <thunderbots/ai_controlConfig.h>
#include <thunderbots/xbox_controllerConfig.h>
#include <thunderbots/vision_and_filtersConfig.h>
#include <thunderbots/aiConfig.h>
#include <thunderbots/enemy_team_capabilityConfig.h>
#include <thunderbots/particle_filterConfig.h>
int main(int argc, char** argv){
ros::init(argc, argv, "dynamic_parameters");
ros::NodeHandle nh_ai_control("/ai_control");
dynamic_reconfigure::Server<param_server::ai_controlConfig> ai_control(nh_ai_control);
ros::NodeHandle nh_xbox_controller("/xbox_controller");
dynamic_reconfigure::Server<param_server::xbox_controllerConfig> xbox_controller(nh_xbox_controller);
ros::NodeHandle nh_vision_and_filters("/vision_and_filters");
dynamic_reconfigure::Server<param_server::vision_and_filtersConfig> vision_and_filters(nh_vision_and_filters);
ros::NodeHandle nh_ai("/ai");
dynamic_reconfigure::Server<param_server::aiConfig> ai(nh_ai);
ros::NodeHandle nh_enemy_team_capability("/enemy_team_capability");
dynamic_reconfigure::Server<param_server::enemy_team_capabilityConfig> enemy_team_capability(nh_enemy_team_capability);
ros::NodeHandle nh_particle_filter("/particle_filter");
dynamic_reconfigure::Server<param_server::particle_filterConfig> particle_filter(nh_particle_filter);
ros::spin();
};